from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field
from typing import Optional, Literal, Any

Status = Literal["ok", "degraded", "down"]

class ChatRequest(BaseModel):
    message: str = Field(
        description="Natural language question or request about the knowledge graph. "
        "The LLM will generate a SPARQL query to answer it."
    )
    session_id: UUID | None = Field(
        default=None,
        description="Session ID for conversation continuity. "
        "If null, a new session is created and the ID is returned in the response."
    )


class ChatResponse(BaseModel):
    answer: str = Field(
        description="Natural language answer generated by the LLM. Based on the SPARQL "
        "query results, or a clarification question if the LLM needed more information."
    )
    session_id: UUID = Field(
        description="Session ID for this conversation. Store this and send it with subsequent requests."
    )
    llm_generated_query: str = Field(
        default="",
        description="SPARQL query generated by the LLM from the user message. "
        "Empty if no query was executed."
    )
    sparql_query_result: Optional[str] = Field(
        default=None,
        description="Raw JSON response from the GraphDB SPARQL endpoint. "
        "Null if no query was executed or on error."
    )

class HistoryMessage(BaseModel):
    role: Literal["user", "assistant"] = Field(
        description="Who produced the message."
    )
    content: str = Field(
        description="The user message or the LLM answer."
    )
    sparql_query: Optional[str] = Field(
        default=None,
        description="SPARQL query associated with this message, if any."
    )
    sparql_results: Optional[str] = Field(
        default=None,
        description="Raw JSON SPARQL results associated with this message, if any."
    )
    created_at: Optional[datetime] = Field(
        default=None,
        description="Server timestamp."
    )

class HistoryResponse(BaseModel):
    session_id: UUID = Field(
        description="Session the messages belong to."
    )
    messages: list[HistoryMessage] = Field(
        description="Full chronological message history of the session."
    )

class ServiceHealth(BaseModel):
    status: Status = Field(
        description='Health status: "ok" (fully operational), "degraded" (partially available), "down" (unavailable).'
    )
    error: Optional[str] = Field(
        default=None,
        description="Error details if status is not 'ok'."
    )
    additional_attributes: dict[str, Any] = Field(
        default_factory=dict,
        description="Service-specific metadata, e.g. checked models or endpoint URL."
    )

class HealthResponse(BaseModel):
    status: str = Field(
        description='Overall health: "ok" (all services healthy), "degraded" (at least one degraded), "down" (at least one down).'
    )
    error: Optional[str] = Field(
        default=None,
        description="Semicolon-separated list of service errors. Null if all services are ok."
    )
    services: dict[str, ServiceHealth] = Field(
        description="Map of service name to its health status. "
        "Contains 'sparql_service' (GraphDB connectivity) and 'llm_service' (LLM API availability)."
    )

class ModelResponse(BaseModel):
    models: set[str] = Field(
        description="Set of model IDs available on the configured LLM API."
    )

class FullTable(BaseModel):
    columns: list[str] = Field(
        description="Ordered column names, as configured in the full_table_columns setting."
    )
    rows: list[dict[str, Any]] = Field(
        description="One object per row, keyed by column name. Numeric cells are coerced "
        "to int/float based on their SPARQL datatype; missing cells are null."
    )

class FullTableResponse(BaseModel):
    full_table: FullTable = Field(
        description="Predefined tabular view of the knowledge graph (columns + rows)."
    )

class ErrorResponse(BaseModel):
    status: Literal["error"] = "error"
    error: str
    detail: str | None = None