class AppException(Exception):
    """Base for all domain exceptions."""
    def __init__(self, message: str = ""):
        self.message = message
        super().__init__(message)

class LLMServiceException(AppException): ...
class LLMNoContentException(AppException): ...
class SparqlDatabaseException(AppException): ...
class SparqlDatabaseStatusCode(AppException): ...
class SparqlQueryException(AppException): ...  # the query itself was bad → recoverable by the LLM
class SessionNotFoundException(AppException): ...  # unknown session id → 404
